name: Code build and review
on: push
jobs:
  buildjob:
   runs-on: ubuntu-latest
   steps: 
    - name: clone the current repo on the runner
      uses: actions/checkout@v4
    - name: Setup java 17 and maven
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Review the code using SonarCloud
      run:  mvn -B verify sonar:sonar -Dsonar.projectKey=sonar-demo-githubaction_project-sonar-demo -Dsonar.organization=sonar-demo-githubaction -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
